version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $CIRCLE_SHA1
      - run:
          name: Start container and test
          command: |
            docker run -d -p 8080:8080 --name app $DOCKER_IMAGE:$CIRCLE_SHA1
            echo "Container started, waiting..."
            sleep 5
            CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app)
            echo "Container IP: $CONTAINER_IP"
            echo "Container logs:"
            docker logs app
            echo "Testing connection..."
            curl --verbose --retry 10 --retry-delay 2 --retry-connrefused http://$CONTAINER_IP:8080 || (docker logs app && exit 1)

  push-docker:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_IMAGE
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - push-docker:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
